<?php

namespace ErpBundle\Repository;

/**
 * TrialDiscussionSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrialDiscussionTRepository extends \Doctrine\ORM\EntityRepository
{
}