<?php

namespace ErpBundle\Repository;

/**
 * TrialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrialsRepository extends \Doctrine\ORM\EntityRepository
{
}
