<?php

namespace ErpBundle\Repository;

/**
 * TrialProtocolFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrialProtocolFileRepository extends \Doctrine\ORM\EntityRepository
{
}