#Erp

erp_homepage:
    path:     /
    defaults:
        _controller: ErpBundle:Default:index

erp_sponsors:
    path:     /sponsors
    defaults:
        _controller: ErpBundle:Sponsor:list

erp_sponsor:
    path:     /sponsor/{id}
    defaults:
        _controller: ErpBundle:Sponsor:view
    requirements:
        id: \d+

erp_trials:
    path: /trials
    defaults:
        _controller: ErpBundle:Trial:list

erp_trial:
    path: /trial/{id}
    defaults:
        _controller: ErpBundle:Trial:view
    requirements:
        id: \d+

erp_trial_demo:
    path: /trial/1
    defaults:
        _controller: ErpBundle:Trial:view
    requirements:
        id: \d+

erp_test:
    path: /test/
    defaults:
        _controller: ErpBundle:Trial:test

#API

api:
    type: rest
    resource: "routing_api.yml"

#FOSUSERBundle

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
