security:
  encoders:
    UserBundle\Entity\User: sha512


  role_hierarchy:
    ROLE_PM:          [ROLE_ADMIN]
    ROLE_ADMIN:       [ROLE_PM]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


  providers:
    main:
      id: fos_user.user_provider.username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main_login:
      # Cette expression régulière permet de prendre /login (mais pas /login_check !)
      pattern:   ^/login$
      anonymous: true # On autorise alors les anonymes sur ce pare-feu
    main:
      pattern:      ^/
      anonymous:    false
      provider:     main
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
      logout:
        path:       fos_user_security_logout
        target:     /login
      remember_me:
        secret:     '%secret%' # %secret% est un paramètre de parameter

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }